# Generated by Django 5.1.2 on 2026-08-30 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Premium tokenized property in Hyderabad')),
                ('location', models.CharField(default='Hyderabad', max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, default=10000000, max_digits=12)),
                ('total_tokens', models.IntegerField(default=1000)),
                ('token_price', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('rental_yield', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1560518883-ce09059eeffa')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_owned', models.IntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='tokenization.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
