# Generated by Django 6.1 on 2026-09-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0002_alter_tokenholding_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenholding',
            name='real_estate',
        ),
        migrations.RemoveField(
            model_name='tokenholding',
            name='tokens_owned',
        ),
        migrations.AddField(
            model_name='tokenholding',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.property'),
        ),
        migrations.AddField(
            model_name='tokenholding',
            name='tokens',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Kokapet, Hyderabad', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Modern Luxury Villa', max_length=200),
        ),
    ]
